config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checks

  # Root route
  root 'notifications#main'

  # Authentication routes
  get '/login' => 'sessions#new'
  post '/login' =>'sessions#create'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'
  delete '/logout' => 'sessions#destroy'

  # User routes
  resources :users, only:[:show, :update, :edit] do
    get 'vehicles', on: :member
    get 'fines', on: :member
  end

  # Notification routes
  resources :notifications do
    patch 'publish', on: :member
  end

  # Vehicle routes
  resources :vehicles

  # Fine routes
  resources :fines, param: :_id do
    get 'payment', on: :member, to: 'payments#new'
    post 'payment', on: :member, to: 'payments#pay'
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  include ActiveModel::Serializers::Xml
  validates :subject, presence: { message: "not inserted" }
  validates :body, presence: { message: "not inserted" }
end

app/controllers/notifications_controller.rb
require 'time'
class NotificationsController < ApplicationController
  include HTTParty
  before_action :administrator_required, only: [:index, :show, :edit, :new]
  before_action :get_notifications_json, only: [:index, :main]
  before_action :get_notification_json, only: [:show, :edit, :update, :destroy, :publish]

  def get_notifications_json
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification"
    response = HTTParty.get(url, basic_auth: auth).parsed_response
    @notifications = []
    response.each do |notification|
      notifications_params = {
        subject: notification["subject"],
        body: notification["body"],
        published: notification["published"],
        created_at: notification["createdAt"],
        updated_at: notification["modifiedAt"]
      }
      received_notification = Notification.new(notifications_params)
      received_notification.id = notification["notificationId"]
      @notifications << received_notification
    end
  end

  def get_notification_json
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification/" + params[:id].to_s
    response = HTTParty.get(url, basic_auth: auth).parsed_response
    notifications_params = {
      id: response["notificationId"],
      subject: response["subject"],
      body: response["body"],
      published: response["published"],
      created_at: response["createdAt"],
      updated_at: response["modifiedAt"]
    }
    @notification = Notification.new(notifications_params)
  end

  def index
    @title = "Notifications List"
    respond_to do |format|
      format.html { }
      format.json {
        render json: @notifications
      }
      format.xml {
        render xml: @notifications
      }
    end
  end

  def show
    @title = "Show Notification"
    respond_to do |format|
      format.html { }
      format.json {
        render json: @notification
      }
      format.xml {
        render xml: @notification
      }
    end
  end

  def new
    @title = "New Notification"
    @notification = Notification.new
  end

  def create
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification"
    notification_subject = notification_params[:subject]
    notification_body = notification_params[:body]
    @notification = Notification.new(notification_params)
    if @notification.valid?
      request = HTTParty.post(url,
        basic_auth: auth,
        headers: {
          "Content-Type": "application/json",
        },
        body: {
          subject: notification_subject,
          body: notification_body,
          published: false,
          createdat: Time.now.iso8601,
          modifiedat: Time.now.iso8601,
        }.to_json)
      flash[:notice] = "Notification added successfully!"
      redirect_to notifications_path
    else
      flash[:error] = "Notification could not be added!"
      render :new
    end
  end

  def edit
    @title = "Edit Notification"
  end

  def update
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification"
    notification_subject = notification_params[:subject]
    notification_body = notification_params[:body]
    @notification.subject = notification_subject
    @notification.body = notification_body
    if @notification.valid?
      request = HTTParty.put(url,
        basic_auth: auth,
        headers: {
          "Content-Type": "application/json",
        },
        body: {
          notificationid: @notification.id,
          subject: @notification.subject,
          body: @notification.body,
          published: @notification.published,
          createdat: @notification.created_at,
          modifiedat: @notification.updated_at,
        }.to_json)
      flash[:notice] = "Notification updated successfully!"
      redirect_to notifications_path
    else
      flash[:error] = "Notification could not be updated!"
      render :edit
    end
  end

  def destroy
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification/" + params[:id].to_s
    response = HTTParty.delete(url, basic_auth: auth)
    if response.code == 200
      flash[:notice] = "Notification deleted successfully!"
      redirect_to notifications_path
    else
      flash[:error] = "Notification could not be deleted!"
      render :index
    end
  end

  def publish
    auth = {username: '11166769', password: '60-dayfreetrial'}
    url = "http://indritcaca-001-site1.ftempurl.com/api/Notification/#{params[:id].to_s}/publish"
    response = HTTParty.get(url, basic_auth: auth)
    puts response
    if response.code == 200
      flash[:notice] = "Notification published successfully!"
      redirect_to notifications_path
    else
      flash[:error] = "Notification could not be published!"
      render :index
    end
  end

  def main
    @title = "Main Page"
    @main_notifications = @notifications.select { |notification| notification["published"] == true}
    @main_notifications.sort { |a, b| a["created_at"] <=> b["created_at"] }
  end

  def notification_params
    params.require(:notification).permit(:subject, :body)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/edit.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">Edit Notification</h2>
    <%= form_tag notification_path(@notification), :method => :put, :class => 'form card-text' do %>
      <%= render partial: "shared/message", locals: { object: @notification } %>
      <div class="mb-3">
        <%= label :notification, :subject, 'Subject', :class => 'form-label' %>
        <%= text_field :notification, :subject, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :notification, :body, 'Body', :class => 'form-label' %>
        <%= text_area :notification, :body, :class => 'form-control' %>
      </div>
      <div class="d-flex justify-content-center">
        <%= submit_tag 'Edit', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <%= render partial: "shared/header_index", locals: { type: 'Notification', path: new_notification_path } %>
  <table class="table table-striped mt-3">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" class="w-50">Subject</th>
      <th scope="col" class="w-50">Created At</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <% if @notifications.any? %>
      <tbody>
      <% @notifications.each_with_index do |notification, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= notification.subject %></td>
          <td><%= time_ago_in_words(notification.created_at - 1.hours) %> ago</td>
          <td>
            <div class="d-flex align-items-end">
              <%= render partial: "shared/crud_buttons",
                         locals: { crud_view_path: notification_path(notification),
                                  crud_edit_path: edit_notification_path(notification),
                                  crud_delete_path: notification_path(notification) } %>
              <% if notification.published %>
                <h6 class="text-success ms-2">Published</h6>
              <% else %>
                <%= button_to "Publish", publish_notification_path(notification), method: :patch, :class => 'btn btn-success ms-2' %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/notifications/main.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <h2>Notifications</h2>
  <% if @main_notifications.any? %>
      <% @main_notifications.each do |main_notification| %>
      <div class='card mt-4'>
        <div class="card-header d-flex justify-content-between">
          <h5 class="align-self-center"><%= main_notification.subject %></h5>
          <small class="align-self-center text-primary"><%= time_ago_in_words(main_notification.created_at) %> ago</small>
        </div>
        <div class="card-body">
          <p class="card-text"><%= main_notification.body %></p>
        </div>
      </div>
      <% end %>
  <% end %>
</div>

app/views/notifications/new.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">New Notification</h2>
    <%= form_tag notifications_path, :method => :post, :class => 'form card-text' do %>
      <%= render partial: "shared/message", locals: { object: @notification } %>
      <div class="mb-3">
        <%= label :notification, :subject, 'Subject', :class => 'form-label' %>
        <%= text_field :notification, :subject, :class => 'form-control', placeholder: "Subject" %>
      </div>
      <div class="mb-3">
        <%= label :notification, :body, 'Body', :class => 'form-label' %>
        <%= text_area :notification, :body, :class => 'form-control', placeholder: "Body" %>
      </div>
      <div class="d-flex justify-content-center">
        <%= submit_tag 'Add', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/notifications/show.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <h2>Notification</h2>
  <div class='card mt-4'>
    <div class="card-header d-flex justify-content-between">
      <h5 class="align-self-center"><%= @notification.subject %></h5>
      <small class="align-self-center text-primary"><%= time_ago_in_words(@notification.created_at) %> ago</small>
    </div>
      <div class="card-body">
        <p class="card-text"><%= @notification.body %></p>
      </div>
    </div>
</div>