config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checks

  # Root route
  root 'notifications#main'

  # Authentication routes
  get '/login' => 'sessions#new'
  post '/login' =>'sessions#create'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'
  delete '/logout' => 'sessions#destroy'

  # User routes
  resources :users, only:[:show, :update, :edit] do
    get 'vehicles', on: :member
    get 'fines', on: :member
  end

  # Notification routes
  resources :notifications do
    patch 'publish', on: :member
  end

  # Vehicle routes
  resources :vehicles

  # Fine routes
  resources :fines, param: :_id do
    get 'payment', on: :member, to: 'payments#new'
    post 'payment', on: :member, to: 'payments#pay'
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: { message: "not inserted" }, uniqueness: { message: "not unique" },
            format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "should be in valid format"}
  validates :password, presence: { message: "not inserted" }
  validates :name, presence: { message: "not inserted" }
  validates :surname, presence: { message: "not inserted" }
  validate :national_identification_number_check
  validate :phone_number_check
  validate :date_of_birth_check
  has_many :vehicles

    def date_of_birth_check
      if date_of_birth.present? && date_of_birth > Date.today
        errors.add(:date_of_birth, "can't be in the future")
      end
    end

  def national_identification_number_check
    if national_identification_number.present?
      unless national_identification_number.match(/[A-Z][0-9]{8}[A-Z]/)
        errors.add(:national_identification_number, "is not in the right format")
      end
    end
  end

  def phone_number_check
    if phone_number.present?
      unless phone_number.match(/(067|068|069)\d{7}/)
        errors.add(:national_identification_number, "is not in the right format")
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only: [:show, :edit, :update]
  before_action :individual_required, only: [:vehicles, :fines]
  before_action :user, only: [:show, :edit, :update, :vehicles, :fines, :check_user]

  def show
    @title = "Show User"
    check_user
  end

  def edit
    @title = "Edit User"
    check_user
  end

  def update
    if @user.update(update_user_params)
      flash[:notice] = "User profile has been updated successfully!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "User profile could not be updated!"
      render :edit
    end
  end

  def vehicles
    @title = "My Vehicles"
    if @user.id == current_user.id
      url = "https://vehicle-api-webapp.onrender.com/vehicles"
      response = HTTParty.get(url).parsed_response
      @vehicles = []
      response.each do |vehicle|
        vehicle_params = {
          plate_number: vehicle["plate_number"],
          vehicle_type: vehicle["vehicle_type"],
          make: vehicle["make"],
          production_year: vehicle["production_year"],
          user_id: vehicle["user_id"],
        }
        received_vehicle = Vehicle.new(vehicle_params)
        received_vehicle.id = vehicle["id"]
        @vehicles << received_vehicle
      end
      @vehicles = @vehicles.select { |vehicle| vehicle.user_id == current_user.id}
    else
      redirect_to user_path(@user)
    end
  end

  def fines
    @title = "My Fines"
    if @user.id == current_user.id
      url = "https://finesapi.onrender.com/fines"
      response = HTTParty.get(url).parsed_response
      @fines = []
      response.each do |fine|
        fine_params = {
          reason: fine["reason"],
          place: fine["place"],
          issue_time: fine["issue_time"],
          amount: fine["amount"],
          payment_status: fine["payment_status"],
          penalty_amount: fine["penalty_amount"],
          user_id: fine["user_id"],
          vehicle_id: fine["vehicle_id"],
          created_at: fine["created_at"],
          updated_at: fine["updated_at"]
        }
        fine_user = User.find_by(id: fine["user_id"])
        vehicle_url_response = HTTParty.get("https://vehicle-api-webapp.onrender.com/vehicles/#{fine["vehicle_id"]}").parsed_response
        received_fine = Fine.new(fine_params)
        received_fine._id = fine["_id"]
        received_fine.user_name = fine_user.name
        received_fine.user_surname = fine_user.surname
        received_fine.vehicle_plate_number = vehicle_url_response["plate_number"]
        @fines << received_fine
      end
      @fines = @fines.select { |fine| fine.user_id == current_user.id}
    else
      redirect_to user_path(@user)
    end
  end

  def update_user_params
    params.require(:user).permit(:name, :surname, :email, :password, :national_identification_number, :phone_number, :date_of_birth)
  end

  def user
    @user = User.find(params[:id])
  end

  def check_user
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/views/users/edit.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">Edit User</h2>
    <%= form_tag user_path(@user), :method => :put, :class => 'form card-text' do %>
      <%= render partial: "shared/message", locals: { object: @user } %>
      <div class="mb-3">
        <%= label :user, :name, 'Name', :class => 'form-label' %>
        <%= text_field :user, :name, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :surname, 'Surname', :class => 'form-label' %>
        <%= text_field :user, :surname, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :email, 'Email', :class => 'form-label' %>
        <%= text_field :user, :email, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :password, 'Password', :class => 'form-label' %>
        <%= text_field :user, :password, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :national_identification_number, 'National Identification Number', :class => 'form-label' %>
        <%= text_field :user, :national_identification_number, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :phone_number, 'Phone Number', :class => 'form-label' %>
        <%= text_field :user, :phone_number, :class => 'form-control' %>
      </div>
      <div class="mb-3">
        <%= label :user, :date_of_birth, 'Date of Birth', :class => 'form-label' %>
        <%= date_select :user, :date_of_birth, :start_year => 1900, :end_year => Date.today.year, :class => 'form-control' %>
      </div>
      <div class="d-flex justify-content-center">
        <%= submit_tag 'Edit', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/fines.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <h2>My Fines</h2>
  <table class="table table-striped mt-3">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Plate number</th>
      <th scope="col">Reason</th>
      <th scope="col">Place</th>
      <th scope="col">Issue Time</th>
      <th scope="col">Amount</th>
      <th scope="col">Payment Status</th>
    </tr>
    </thead>
    <% if @fines.any? %>
      <tbody>
      <% @fines.each_with_index do |fine, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= fine.vehicle_plate_number %></td>
          <td><%= fine.reason %></td>
          <td><%= fine.place %></td>
          <td><%= fine.issue_time.strftime("%d/%m/%Y %H:%M") %></td>
          <td><%= sprintf('%.2f', fine.amount + (fine.penalty_amount ? fine.penalty_amount : 0.00)) %></td>
          <td>
            <% if fine.payment_status %>
              <span class="text-success ms-2">Paid</span>
            <% else %>
              <%= button_to "Pay", payment_fine_path(fine._id), method: :get, :class => 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body d-flex justify-content-between align-items-center">
    <h2 class="card-title">My Profile</h2>
    <div class="btn-group" role="group">
      <%= link_to 'Edit profile', edit_user_path(@user), :class => 'card-link btn ms-1 btn-primary' %>
      <% if @user.role == "Individual" %>
        <%= link_to 'My vehicles', vehicles_user_path(@user), :class => 'card-link btn ms-1 btn-primary' %>
        <%= link_to 'My fines', fines_user_path(@user), :class => 'card-link btn ms-1 btn-primary' %>
      <% end %>
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><h5>Full Name: <small class="text-muted"><%= @user.name %> <%= @user.surname %></small></h5></li>
    <li class="list-group-item"><h5>Email: <small class="text-muted"><%= @user.email %></small></h5></li>
    <li class="list-group-item"><h5>Password: <small class="text-muted"><%= @user.password %></small></h5></li>
    <li class="list-group-item"><h5>National Identification Number (NID): <small class="text-muted"><%= @user.national_identification_number %></small></h5></li>
    <li class="list-group-item"><h5>Phone number: <small class="text-muted"><%= @user.phone_number %></small></h5></li>
    <li class="list-group-item"><h5>Date of birth: <small class="text-muted"><%= @user.date_of_birth ? @user.date_of_birth.strftime("%d/%m/%Y") : @user.date_of_birth %></small></h5></li>
  </ul>
</div>

app/views/users/vehicles.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <h2>My Vehicles</h2>
  <table class="table table-striped mt-3">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" class="w-25">Plate number</th>
      <th scope="col" class="w-25">Vehicle type</th>
      <th scope="col" class="w-25">Make</th>
      <th scope="col" class="w-25">Production year</th>
    </tr>
    </thead>
    <% if @vehicles.any? %>
      <tbody>
      <% @vehicles.each_with_index do |vehicle, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= vehicle.plate_number %></td>
          <td><%= vehicle.vehicle_type %></td>
          <td><%= vehicle.make %></td>
          <td><%= vehicle.production_year %></td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>
</div>