config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checks

  # Root route
  root 'notifications#main'

  # Authentication routes
  get '/login' => 'sessions#new'
  post '/login' =>'sessions#create'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'
  delete '/logout' => 'sessions#destroy'

  # User routes
  resources :users, only:[:show, :update, :edit] do
    get 'vehicles', on: :member
    get 'fines', on: :member
  end

  # Notification routes
  resources :notifications do
    patch 'publish', on: :member
  end

  # Vehicle routes
  resources :vehicles

  # Fine routes
  resources :fines, param: :_id do
    get 'payment', on: :member, to: 'payments#new'
    post 'payment', on: :member, to: 'payments#pay'
  end

end

app/views/shared/_crud_buttons.html.erb
<%= button_to "View", crud_view_path, method: :get, :class => 'btn btn-info text-white ms-2' %>
<%= button_to "Edit", crud_edit_path, method: :get, :class => 'btn btn-primary ms-2' %>
<%= button_to "Delete", crud_delete_path, method: :delete, :class => 'btn btn-danger ms-2' %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_header_index.html.erb
<div class="d-flex align justify-content-between align-items-center">
  <h2>Manage <%= type %>s</h2>
  <%= link_to 'Add ' + type, path, :class => 'card-link btn btn-success' %>
</div>

app/views/shared/_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <% object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark ">
  <div class="container-fluid align-items-baseline">
    <div class="brand_data">
      <h5 class="navbar-brand text-white">Traffic Application</h5>
    </div>
    <div class="logged_data d-flex align-items-center">
      <div class="d-flex ms-1">
        <% if current_user %>
          <a class="navbar-brand text-white"><%= current_user.name.concat(" ").concat(current_user.surname) %></a>
        <% else %>
          <a class="navbar-brand text-white">Not logged in</a>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-white ms-1" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_user%>
            <% if current_user.role == 'Administrator' %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Administration
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><%= link_to "Notifications administration", notifications_path, :class => 'dropdown-item'%></li>
                  <li><%= link_to "Vehicles administration", vehicles_path, :class => 'dropdown-item' %></li>
                  <li><%= link_to "Fines administration", fines_path, :class => 'dropdown-item' %></li>
                </ul>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="d-flex">
        <% if current_user %>
          <%= link_to "My profile", user_path(current_user), :class => 'btn btn-primary ms-2' %>
          <%= button_to "Logout", logout_path, :method => "delete", :class => 'btn btn-danger ms-2' %>
        <% else %>
          <%= button_to "Login", login_path, :method => "get", :class => 'btn btn-primary ms-2' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>