config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checks

  # Root route
  root 'notifications#main'

  # Authentication routes
  get '/login' => 'sessions#new'
  post '/login' =>'sessions#create'
  get '/signup' => 'registrations#new'
  post '/signup' => 'registrations#create'
  delete '/logout' => 'sessions#destroy'

  # User routes
  resources :users, only:[:show, :update, :edit] do
    get 'vehicles', on: :member
    get 'fines', on: :member
  end

  # Notification routes
  resources :notifications do
    patch 'publish', on: :member
  end

  # Vehicle routes
  resources :vehicles

  # Fine routes
  resources :fines, param: :_id do
    get 'payment', on: :member, to: 'payments#new'
    post 'payment', on: :member, to: 'payments#pay'
  end

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :plate_number, presence: { message: "not inserted" },
            uniqueness: { message: "already exists" }
  belongs_to :user
end

app/controllers/vehicles_controller.rb
require 'time'
class VehiclesController < ApplicationController
  include HTTParty
  before_action :vehicle_user, only: [:create, :update]
  before_action :get_vehicles_json, only: [:index]
  before_action :get_vehicle_json, only: [:show, :edit, :update, :destroy]
  before_action :administrator_required, only: [:index, :show, :edit, :new]

  def get_vehicles_json
    url = "https://vehicle-api-webapp.onrender.com/vehicles"
    response = HTTParty.get(url).parsed_response
    @vehicles = []
    response.each do |vehicle|
      vehicle_params = {
        plate_number: vehicle["plate_number"],
        vehicle_type: vehicle["vehicle_type"],
        make: vehicle["make"],
        production_year: vehicle["production_year"],
        user_id: vehicle["user_id"],
      }
      received_vehicle = Vehicle.new(vehicle_params)
      received_vehicle.id = vehicle["id"]
      @vehicles << received_vehicle
    end
  end

  def get_vehicle_json
    url = "https://vehicle-api-webapp.onrender.com/vehicles/" + params[:id].to_s
    response = HTTParty.get(url).parsed_response
    vehicle_params = {
      id: response["id"],
      plate_number: response["plate_number"],
      vehicle_type: response["vehicle_type"],
      make: response["make"],
      production_year: response["production_year"],
      user_id: response["user_id"]
    }
    puts vehicle_params
    @vehicle = Vehicle.new(vehicle_params)
  end

  def index
    @title = "Vehicles List"
    respond_to do |format|
      format.html { }
      format.json {
        render json: @vehicles
      }
      format.xml {
        render xml: @vehicles
      }
    end
  end

  def show
    @title = "Show Vehicle"
    @vehicle_user = User.find_by(id: @vehicle.user_id)
    respond_to do |format|
      format.html {
      }
      format.json {
        render json: @vehicle
      }
      format.xml {
        render xml: @vehicle
      }
    end
  end

  def new
    @title = "New Vehicle"
    @vehicle = Vehicle.new
  end

  def create
    url = "https://vehicle-api-webapp.onrender.com/vehicles"
    vehicle_plate_number = vehicle_params[:plate_number]
    vehicle_type = vehicle_params[:vehicle_type]
    vehicle_make = vehicle_params[:make]
    vehicle_production_year = vehicle_params[:production_year]
    vehicle_user_id = vehicle_params[:user_id]
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.valid?
      request = HTTParty.post(url,
                              headers: {
                                "Content-Type": "application/json",
                              },
                              body: {
                                plate_number: vehicle_plate_number,
                                vehicle_type: vehicle_type,
                                make: vehicle_make,
                                production_year: vehicle_production_year,
                                user_id: vehicle_user_id
                              }.to_json)
      flash[:notice] = "Vehicle added successfully!"
      redirect_to vehicles_path
    else
      flash[:error] = "Vehicle could not be added"
      render :new
    end
  end

  def edit
    @title = "Edit Vehicle"
  end

  def update
    url = "https://vehicle-api-webapp.onrender.com/vehicles/" + params[:id].to_s
    vehicle_plate_number = vehicle_params[:plate_number]
    vehicle_type = vehicle_params[:vehicle_type]
    vehicle_make = vehicle_params[:make]
    vehicle_production_year = vehicle_params[:production_year]
    vehicle_user_id = vehicle_params[:user_id]
    @vehicle.plate_number = vehicle_plate_number
    @vehicle.vehicle_type = vehicle_type
    @vehicle.make = vehicle_make
    @vehicle.production_year = vehicle_production_year
    @vehicle.user_id = vehicle_user_id
    if @vehicle.valid?
      puts "Vehicle valid"
      request = HTTParty.put(url,
                             headers: {
                               "Content-Type": "application/json",
                             },
                             body: {
                               plate_number: @vehicle.plate_number,
                               vehicle_type: @vehicle.vehicle_type,
                               make: @vehicle.make,
                               production_year: @vehicle.production_year,
                               user_id: @vehicle.user_id
                             }.to_json)
      flash[:notice] = "Vehicle updated successfully!"
      redirect_to vehicles_path
    else
      puts "Vehicle not valid"
      flash[:error] = "Vehicle could not be updated"
      render :edit
    end
  end

  def destroy
    url = "https://vehicle-api-webapp.onrender.com/vehicles/" + params[:id].to_s
    response = HTTParty.delete(url)
    if response.code == 200
      flash[:notice] = "Vehicle deleted successfully!"
      redirect_to vehicles_path
    else
      flash[:error] = "Vehicle could not be deleted"
      render :index
    end
  end

  def vehicle_params
    params.require(:vehicle).permit(:plate_number, :vehicle_type, :make, :production_year, :user_id)
  end

  def vehicle_user_param
    params.require(:vehicle).permit(:user_id)
  end

  def vehicle_user
    @user = User.find(vehicle_user_param["user_id"])
  end

  def vehicle
    @vehicle = Vehicle.find(params[:id])
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/edit.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">Edit Vehicle</h2>
    <%= form_tag vehicle_path(@vehicle), :method => :put, :class => 'form card-text' do %>
      <%= render partial: "shared/message", locals: { object: @vehicle } %>
      <div class="mb-3">
        <%= label :vehicle, :plate_number, 'Plate Number', :class => 'form-label' %>
        <%= text_field :vehicle, :plate_number, :class => 'form-control', placeholder: "AA000TR" %>
      </div>
      <div class="mb-3">
        <%= label :vehicle, :vehicle_type, 'Type', :class => 'form-label' %>
        <%= text_area :vehicle, :vehicle_type, :class => 'form-control', placeholder: "Sports car" %>
      </div>
      <div class="mb-3">
        <%= label :vehicle, :make, 'Make', :class => 'form-label' %>
        <%= text_field :vehicle, :make, :class => 'form-control', placeholder: "Ferrari" %>
      </div>
      <div class="mb-3 d-block w-100">
        <%= label :vehicle, :production_year, 'Production Year', :class => 'form-label' %>
        <%= select :vehicle, :production_year, (Date.today.year-50)..(Date.today.year), {}, { :class => 'form-control d-block w-100' }%>
      </div>
      <div class="mb-3 d-block w-100">
        <%= label :vehicle, :user_id, 'User', :class => 'form-label' %>
        <%= select :vehicle, :user_id, User.where(role: "Individual").all.map{|user| [user.name + " " + user.surname, user.id]}, {}, { :class => 'form-control d-block w-100' }%>
      </div>
      <div class="d-flex justify-content-center">
        <%= submit_tag 'Edit', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="mw-100 w-75 p-4 m-5">
  <%= render partial: "shared/header_index", locals: { type: 'Vehicle', path: new_vehicle_path } %>
  <table class="table table-striped mt-3">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Plate Number</th>
      <th scope="col">User</th>
      <th scope="col">Type</th>
      <th scope="col">Make</th>
      <th scope="col">Production Year</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <% if @vehicles.any? %>
      <tbody>
      <% @vehicles.each_with_index do |vehicle, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= vehicle.plate_number %></td>
          <td><%= User.where(id: vehicle.user_id).all.map{|user| user.name + " " + user.surname }.join(" ") %></td>
          <td><%= vehicle.vehicle_type %></td>
          <td><%= vehicle.make %></td>
          <td><%= vehicle.production_year %></td>
          <td>
            <div class="d-flex align-items-end">
              <%= render partial: "shared/crud_buttons",
                         locals: { crud_view_path: vehicle_path(vehicle),
                                  crud_edit_path: edit_vehicle_path(vehicle),
                                  crud_delete_path: vehicle_path(vehicle) } %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/vehicles/new.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">New Vehicle</h2>
    <%= form_tag vehicles_path, :method => :post, :class => 'form card-text' do %>
      <%= render partial: "shared/message", locals: { object: @vehicle } %>
      <div class="mb-3">
        <%= label :vehicle, :plate_number, 'Plate Number', :class => 'form-label' %>
        <%= text_field :vehicle, :plate_number, :class => 'form-control', placeholder: "AA000TR" %>
      </div>
      <div class="mb-3">
        <%= label :vehicle, :vehicle_type, 'Type', :class => 'form-label' %>
        <%= text_area :vehicle, :vehicle_type, :class => 'form-control', placeholder: "Sports car" %>
      </div>
      <div class="mb-3">
        <%= label :vehicle, :make, 'Make', :class => 'form-label' %>
        <%= text_field :vehicle, :make, :class => 'form-control', placeholder: "Ferrari" %>
      </div>
      <div class="mb-3 d-block w-100">
        <%= label :vehicle, :production_year, 'Production Year', :class => 'form-label' %>
        <%= select :vehicle, :production_year, (Date.today.year-50)..(Date.today.year), {}, { :class => 'form-control d-block w-100' }%>
      </div>
      <div class="mb-3 d-block w-100">
        <%= label :vehicle, :user_id, 'User', :class => 'form-label' %>
        <%= select :vehicle, :user_id, User.where(role: "Individual").all.map{|user| [user.name + " " + user.surname, user.id]}, {}, { :class => 'form-control d-block w-100' }%>
      </div>
      <div class="d-flex justify-content-center">
        <%= submit_tag 'Add', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="card mw-100 w-50 p-4 m-5">
  <div class="card-body">
    <h2 class="card-title">Vehicle information</h2>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><h5>User: <small class="text-muted"><%= @vehicle_user.name %> <%= @vehicle_user.surname %></small></h5></li>
    <li class="list-group-item"><h5>Plate number: <small class="text-muted"><%= @vehicle.plate_number %></small></h5></li>
    <li class="list-group-item"><h5>Vehicle type: <small class="text-muted"><%= @vehicle.vehicle_type %></small></h5></li>
    <li class="list-group-item"><h5>Make: <small class="text-muted"><%= @vehicle.make %></small></h5></li>
    <li class="list-group-item"><h5>Production year: <small class="text-muted"><%= @vehicle.production_year %></small></h5></li>
  </ul>
</div>